// NY State Senator and Assembly member data by district number
// Source: Ballotpedia, current as of March 2026

interface MemberInfo {
  name: string;
  party: 'D' | 'R';
}

export interface DistrictInfo {
  senate_district: string;
  assembly_district: string;
  senator_name: string;
  senator_party: string;
  assembly_member_name: string;
  assembly_member_party: string;
}

// All 63 NY State Senators
const SENATORS: Record<string, MemberInfo> = {
  '1': { name: 'Anthony Palumbo', party: 'R' },
  '2': { name: 'Mario Mattera', party: 'R' },
  '3': { name: 'Dean Murray', party: 'R' },
  '4': { name: 'Monica Martinez', party: 'D' },
  '5': { name: 'Steven Rhoads', party: 'R' },
  '6': { name: 'Siela Bynoe', party: 'D' },
  '7': { name: 'Jack Martins', party: 'R' },
  '8': { name: 'Alexis Weik', party: 'R' },
  '9': { name: 'Patricia Canzoneri-Fitzpatrick', party: 'R' },
  '10': { name: 'James Sanders Jr.', party: 'D' },
  '11': { name: 'Toby Ann Stavisky', party: 'D' },
  '12': { name: 'Michael Gianaris', party: 'D' },
  '13': { name: 'Jessica Ramos', party: 'D' },
  '14': { name: 'Leroy Comrie', party: 'D' },
  '15': { name: 'Joseph Addabbo', party: 'D' },
  '16': { name: 'John Liu', party: 'D' },
  '17': { name: 'Steve Chan', party: 'R' },
  '18': { name: 'Julia Salazar', party: 'D' },
  '19': { name: 'Roxanne Persaud', party: 'D' },
  '20': { name: 'Zellnor Myrie', party: 'D' },
  '21': { name: 'Kevin Parker', party: 'D' },
  '22': { name: 'Sam Sutton', party: 'D' },
  '23': { name: 'Jessica Scarcella-Spanton', party: 'D' },
  '24': { name: 'Andrew Lanza', party: 'R' },
  '25': { name: 'Jabari Brisport', party: 'D' },
  '26': { name: 'Andrew Gounardes', party: 'D' },
  '27': { name: 'Brian Kavanagh', party: 'D' },
  '28': { name: 'Liz Krueger', party: 'D' },
  '29': { name: 'Jose M. Serrano', party: 'D' },
  '30': { name: 'Cordell Cleare', party: 'D' },
  '31': { name: 'Robert Jackson', party: 'D' },
  '32': { name: 'Luis Sepúlveda', party: 'D' },
  '33': { name: 'J. Gustavo Rivera', party: 'D' },
  '34': { name: 'Nathalia Fernandez', party: 'D' },
  '35': { name: 'Andrea Stewart-Cousins', party: 'D' },
  '36': { name: 'Jamaal Bailey', party: 'D' },
  '37': { name: 'Shelley Mayer', party: 'D' },
  '38': { name: 'William Weber Jr.', party: 'R' },
  '39': { name: 'Robert Rolison', party: 'R' },
  '40': { name: 'Peter Harckham', party: 'D' },
  '41': { name: 'Michelle Hinchey', party: 'D' },
  '42': { name: 'James Skoufis', party: 'D' },
  '43': { name: 'Jacob Ashby', party: 'R' },
  '44': { name: 'James Tedisco', party: 'R' },
  '45': { name: 'Dan Stec', party: 'R' },
  '46': { name: 'Patricia Fahy', party: 'D' },
  '47': { name: 'Erik Bottcher', party: 'D' },
  '48': { name: 'Rachel May', party: 'D' },
  '49': { name: 'Mark Walczyk', party: 'R' },
  '50': { name: 'Christopher Ryan', party: 'D' },
  '51': { name: 'Peter Oberacker', party: 'R' },
  '52': { name: 'Lea Webb', party: 'D' },
  '53': { name: 'Joseph Griffo', party: 'R' },
  '54': { name: 'Pamela Helming', party: 'R' },
  '55': { name: 'Samra Brouk', party: 'D' },
  '56': { name: 'Jeremy Cooney', party: 'D' },
  '57': { name: 'George Borrello', party: 'R' },
  '58': { name: 'Thomas O\'Mara', party: 'R' },
  '59': { name: 'Kristen Gonzalez', party: 'D' },
  '60': { name: 'Patrick Gallivan', party: 'R' },
  '61': { name: 'Jeremy Zellner', party: 'D' },
  '62': { name: 'Robert Ortt', party: 'R' },
  '63': { name: 'April Baskin', party: 'D' },
};

// All 150 NY Assembly Members
const ASSEMBLY_MEMBERS: Record<string, MemberInfo> = {
  '1': { name: 'Thomas Schiavoni', party: 'D' },
  '2': { name: 'Jodi Giglio', party: 'R' },
  '3': { name: 'Joseph DeStefano', party: 'R' },
  '4': { name: 'Rebecca Kassay', party: 'D' },
  '5': { name: 'Doug Smith', party: 'R' },
  '6': { name: 'Philip Ramos', party: 'D' },
  '7': { name: 'Jarett Gandolfo', party: 'R' },
  '8': { name: 'Michael Fitzpatrick', party: 'R' },
  '9': { name: 'Michael Durso', party: 'R' },
  '10': { name: 'Steve Stern', party: 'D' },
  '11': { name: 'Kwani O\'Pharrow', party: 'D' },
  '12': { name: 'Keith Brown', party: 'R' },
  '13': { name: 'Charles Lavine', party: 'D' },
  '14': { name: 'David McDonough', party: 'R' },
  '15': { name: 'Jake Blumencranz', party: 'R' },
  '16': { name: 'Daniel Norber', party: 'R' },
  '17': { name: 'John Mikulin', party: 'R' },
  '18': { name: 'Noah Burroughs', party: 'D' },
  '19': { name: 'Edward Ra', party: 'R' },
  '20': { name: 'Eric Ari Brown', party: 'R' },
  '21': { name: 'Judy Griffin', party: 'D' },
  '22': { name: 'Michaelle Solages', party: 'D' },
  '23': { name: 'Stacey G. Pheffer Amato', party: 'D' },
  '24': { name: 'David Weprin', party: 'D' },
  '25': { name: 'Nily Rozic', party: 'D' },
  '26': { name: 'Edward Braunstein', party: 'D' },
  '27': { name: 'Sam Berger', party: 'D' },
  '28': { name: 'Andrew Hevesi', party: 'D' },
  '29': { name: 'Alicia Hyndman', party: 'D' },
  '30': { name: 'Steven Raga', party: 'D' },
  '31': { name: 'Khaleel Anderson', party: 'D' },
  '32': { name: 'Vivian Cook', party: 'D' },
  '33': { name: 'Clyde Vanel', party: 'D' },
  '34': { name: 'Jessica González-Rojas', party: 'D' },
  '35': { name: 'Larinda Hooks', party: 'D' },
  '36': { name: 'Diana Moreno', party: 'D' },
  '37': { name: 'Claire Valdez', party: 'D' },
  '38': { name: 'Jenifer Rajkumar', party: 'D' },
  '39': { name: 'Catalina Cruz', party: 'D' },
  '40': { name: 'Ron Kim', party: 'D' },
  '41': { name: 'Kalman Yeger', party: 'D' },
  '42': { name: 'Rodneyse Bichotte Hermelyn', party: 'D' },
  '43': { name: 'Brian A. Cunningham', party: 'D' },
  '44': { name: 'Robert C. Carroll', party: 'D' },
  '45': { name: 'Michael Novakhov', party: 'R' },
  '46': { name: 'Alec Brook-Krasny', party: 'R' },
  '47': { name: 'William Colton', party: 'D' },
  '48': { name: 'Simcha Eichenstein', party: 'D' },
  '49': { name: 'Lester Chang', party: 'R' },
  '50': { name: 'Emily Gallagher', party: 'D' },
  '51': { name: 'Marcela Mitaynes', party: 'D' },
  '52': { name: 'Jo Anne Simon', party: 'D' },
  '53': { name: 'Maritza Davila', party: 'D' },
  '54': { name: 'Erik Dilan', party: 'D' },
  '55': { name: 'Latrice Walker', party: 'D' },
  '56': { name: 'Stefani Zinerman', party: 'D' },
  '57': { name: 'Phara Souffrant Forrest', party: 'D' },
  '58': { name: 'Monique Chandler-Waterman', party: 'D' },
  '59': { name: 'Jaime Williams', party: 'D' },
  '60': { name: 'Nikki Lucas', party: 'D' },
  '61': { name: 'Charles Fall', party: 'D' },
  '62': { name: 'Michael Reilly', party: 'R' },
  '63': { name: 'Samuel Pirozzolo', party: 'R' },
  '64': { name: 'Michael Tannousis', party: 'R' },
  '65': { name: 'Grace Lee', party: 'D' },
  '66': { name: 'Deborah Glick', party: 'D' },
  '67': { name: 'Linda Rosenthal', party: 'D' },
  '68': { name: 'Eddie Gibbs', party: 'D' },
  '69': { name: 'Micah Lasher', party: 'D' },
  '70': { name: 'Jordan Wright', party: 'D' },
  '71': { name: 'Alfred Taylor', party: 'D' },
  '72': { name: 'Manny De Los Santos', party: 'D' },
  '73': { name: 'Alex Bores', party: 'D' },
  '74': { name: 'Keith Powers', party: 'D' },
  '75': { name: 'Tony Simone', party: 'D' },
  '76': { name: 'Rebecca Seawright', party: 'D' },
  '77': { name: 'Landon Dais', party: 'D' },
  '78': { name: 'George Alvarez', party: 'D' },
  '79': { name: 'Chantel Jackson', party: 'D' },
  '80': { name: 'John Zaccaro Jr.', party: 'D' },
  '81': { name: 'Jeffrey Dinowitz', party: 'D' },
  '82': { name: 'Michael Benedetto', party: 'D' },
  '83': { name: 'Carl Heastie', party: 'D' },
  '84': { name: 'Amanda Septimo', party: 'D' },
  '85': { name: 'Emerita Torres', party: 'D' },
  '86': { name: 'Yudelka Tapia', party: 'D' },
  '87': { name: 'Karines Reyes', party: 'D' },
  '88': { name: 'Amy Paulin', party: 'D' },
  '89': { name: 'J. Gary Pretlow', party: 'D' },
  '90': { name: 'Nader Sayegh', party: 'D' },
  '91': { name: 'Steven Otis', party: 'D' },
  '92': { name: 'Maryjane Shimsky', party: 'D' },
  '93': { name: 'Chris Burdick', party: 'D' },
  '94': { name: 'Matthew Slater', party: 'R' },
  '95': { name: 'Dana Levenberg', party: 'D' },
  '96': { name: 'Patrick Carroll', party: 'D' },
  '97': { name: 'Aron Wieder', party: 'D' },
  '98': { name: 'Karl Brabenec', party: 'R' },
  '99': { name: 'Christopher Eachus', party: 'D' },
  '100': { name: 'Paula Kay', party: 'D' },
  '101': { name: 'Brian Maher', party: 'R' },
  '102': { name: 'Christopher Tague', party: 'R' },
  '103': { name: 'Sarahana Shrestha', party: 'D' },
  '104': { name: 'Jonathan Jacobson', party: 'D' },
  '105': { name: 'Anil Beephan Jr.', party: 'R' },
  '106': { name: 'Didi Barrett', party: 'D' },
  '107': { name: 'Scott H. Bendett', party: 'R' },
  '108': { name: 'John T. McDonald III', party: 'D' },
  '109': { name: 'Gabriella Romero', party: 'D' },
  '110': { name: 'Phil Steck', party: 'D' },
  '111': { name: 'Angelo Santabarbara', party: 'D' },
  '112': { name: 'Mary Beth Walsh', party: 'R' },
  '113': { name: 'Carrie Woerner', party: 'D' },
  '114': { name: 'Matthew Simpson', party: 'R' },
  '115': { name: 'Michael Cashman', party: 'D' },
  '116': { name: 'Scott Gray', party: 'R' },
  '117': { name: 'Kenneth Blankenbush', party: 'R' },
  '118': { name: 'Robert Smullen', party: 'R' },
  '119': { name: 'Marianne Buttenschon', party: 'D' },
  '120': { name: 'William Barclay', party: 'R' },
  '121': { name: 'Joe Angelino', party: 'R' },
  '122': { name: 'Brian Miller', party: 'R' },
  '123': { name: 'Donna Lupardo', party: 'D' },
  '124': { name: 'Christopher Friend', party: 'R' },
  '125': { name: 'Anna Kelles', party: 'D' },
  '126': { name: 'John Lemondes Jr.', party: 'R' },
  '127': { name: 'Al Stirpe', party: 'D' },
  '128': { name: 'Pamela Hunter', party: 'D' },
  '129': { name: 'William Magnarelli', party: 'D' },
  '130': { name: 'Brian Manktelow', party: 'R' },
  '131': { name: 'Jeff Gallahan', party: 'R' },
  '132': { name: 'Philip Palmesano', party: 'R' },
  '133': { name: 'Andrea K. Bailey', party: 'R' },
  '134': { name: 'Josh Jensen', party: 'R' },
  '135': { name: 'Jennifer Lunsford', party: 'D' },
  '136': { name: 'Sarah Clark', party: 'D' },
  '137': { name: 'Demond Meeks', party: 'D' },
  '138': { name: 'Harry Bronson', party: 'D' },
  '139': { name: 'Stephen Hawley', party: 'R' },
  '140': { name: 'William Conrad', party: 'D' },
  '141': { name: 'Crystal Peoples-Stokes', party: 'D' },
  '142': { name: 'Patrick Burke', party: 'D' },
  '143': { name: 'Patrick Chludzinski', party: 'R' },
  '144': { name: 'Paul Bologna', party: 'R' },
  '145': { name: 'Angelo J. Morinello', party: 'R' },
  '146': { name: 'Karen McMahon', party: 'D' },
  '147': { name: 'David DiPietro', party: 'R' },
  '148': { name: 'Joe Sempolinski', party: 'R' },
  '149': { name: 'Jonathan Rivera', party: 'D' },
  '150': { name: 'Andrew Molitor', party: 'R' },
};

export function getSenator(district: string): MemberInfo | null {
  return SENATORS[district] || null;
}

export function getAssemblyMember(district: string): MemberInfo | null {
  return ASSEMBLY_MEMBERS[district] || null;
}

export function buildDistrictInfo(senateDistrict: string, assemblyDistrict: string): DistrictInfo | null {
  const senator = getSenator(senateDistrict);
  const assembly = getAssemblyMember(assemblyDistrict);

  if (!senator || !assembly) return null;

  return {
    senate_district: senateDistrict,
    assembly_district: assemblyDistrict,
    senator_name: senator.name,
    senator_party: senator.party,
    assembly_member_name: assembly.name,
    assembly_member_party: assembly.party,
  };
}
